# Generated by Django 5.1.3 on 2024-11-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
