# Generated by Django 5.1.3 on 2024-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_appointment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=100)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('contactSubject', models.CharField(max_length=15)),
                ('contactMessage', models.CharField(max_length=100)),
            ],
        ),
    ]
